name: Build and push docker images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push mainapp
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mainapp:latest ./TTS
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mainapp:latest

      - name: Build and push adminapp
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/adminapp:latest ./Admin/AdminApplication
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/adminapp:latest

  refresh-azure:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Restart Main Azure Web App
        run: |
          az webapp restart --name ttsapp --resource-group TTS

      - name: Restart Admin Azure Web App
        run: |
          az webapp restart --name ttsadminapp --resource-group TTS

